services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"  # พอร์ตสำหรับเข้าถึง GUI
      - "8000:8000"  # พอร์ตสำหรับ Edge Agent (ถ้าจำเป็น)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - portainer-agent-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer-agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  portainer-agent-network:
    driver: overlay

volumes:
  portainer-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/psf/NFS/portainer-data
